### ISSUE TITLE
Problem compiling 

### ISSUE THREAD

**Issue by ShibeTemple** [jrbudda/Vivecraft_114#1]
Running build.bat yields an error:
```
'"C:\Program Files\Java\jdk-12.0.1\bin\javac" -Xlint:-options -g -source 1.8 -target 1.8 -classpath "jars\versions\1.14.3\1.14.3.jar;lib;lib\*;jars\libraries\com\google\code\findbugs\jsr305\3.0.1\jsr305-3.0.1.jar;jars\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;jars\libraries\org\lwjgl\lwjgl-stb\3.2.2\lwjgl-stb-3.2.2.jar;jars\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;jars\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;jars\libraries\org\apache\logging\log4j\log4j-api\2.8.1\log4j-api-2.8.1.jar;jars\libraries\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar;jars\libraries\org\lwjgl\lwjgl\3.2.2\lwjgl-3.2.2-natives-windows.jar;jars\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;jars\libraries\com\sun\jna\4.2.1\jna-4.2.1.jar;jars\libraries\org\lwjgl\lwjgl-stb\3.2.2\lwjgl-stb-3.2.2-natives-windows.jar;jars\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar;jars\libraries\com\mojang\text2speech\1.11.3\text2speech-1.11.3.jar;jars\libraries\com\mojang\datafixerupper\2.0.24\datafixerupper-2.0.24.jar;jars\libraries\com\google\guava\guava\21.0\guava-21.0.jar;jars\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar;jars\libraries\org\lwjgl\lwjgl-jemalloc\3.2.2\lwjgl-jemalloc-3.2.2.jar;jars\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;jars\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;jars\libraries\com\mojang\text2speech\1.11.3\text2speech-1.11.3-natives-windows.jar;jars\libraries\it\unimi\dsi\fastutil\8.2.1\fastutil-8.2.1.jar;jars\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar;jars\libraries\com\mojang\javabridge\1.0.22\javabridge-1.0.22.jar;jars\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar;jars\libraries\org\json\json\20140107\json-20140107.jar;jars\libraries\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;jars\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;jars\libraries\com\mojang\patchy\1.1\patchy-1.1.jar;jars\libraries\org\lwjgl\lwjgl-opengl\3.2.2\lwjgl-opengl-3.2.2.jar;jars\libraries\org\lwjgl\lwjgl-jemalloc\3.2.2\lwjgl-jemalloc-3.2.2-natives-windows.jar;jars\libraries\org\lwjgl\lwjgl-glfw\3.2.2\lwjgl-glfw-3.2.2.jar;jars\libraries\com\mojang\brigadier\1.0.17\brigadier-1.0.17.jar;jars\libraries\org\lwjgl\lwjgl-opengl\3.2.2\lwjgl-opengl-3.2.2-natives-windows.jar;jars\libraries\org\lwjgl\lwjgl\3.2.2\lwjgl-3.2.2.jar;jars\libraries\commons-io\commons-io\2.5\commons-io-2.5.jar;jars\libraries\com\mojang\realms\1.14.17\realms-1.14.17.jar;jars\libraries\com\mojang\authlib\1.5.25\authlib-1.5.25.jar;jars\libraries\com\google\code\gson\gson\2.8.0\gson-2.8.0.jar;jars\libraries\org\lwjgl\lwjgl-glfw\3.2.2\lwjgl-glfw-3.2.2-natives-windows.jar;jars\libraries\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar;jars\libraries\org\lwjgl\lwjgl-openal\3.2.2\lwjgl-openal-3.2.2.jar;jars\libraries\de\fruitfly\ovr\JRift\0.8.0.0.1\JRift-0.8.0.0.1.jar;jars\libraries\org\apache\logging\log4j\log4j-core\2.8.1\log4j-core-2.8.1.jar;jars\libraries\org\lwjgl\lwjgl-openal\3.2.2\lwjgl-openal-3.2.2-natives-windows.jar;jars\libraries\io\netty\netty-all\4.1.25.Final\netty-all-4.1.25.Final.jar" -sourcepath src\minecraft -d bin\minecraft @temp\java_src_client.txt' failed : 1

== ERRORS FOUND in JAVA CODE ==

src\minecraft\net\minecraft\util\HttpUtil.java:28: error: class HTTPUtil is public, should be declared in a file named HTTPUtil.java
public class HTTPUtil
       ^

src\minecraft\net\minecraft\server\dedicated\ServerProperties.java:61: error: cannot find symbol
    public final PropertyManager<ServerProperties>.a<Integer> playerIdleTimeout;
                                                  ^

  symbol:   class a
  location: class PropertyManager<ServerProperties>
src\minecraft\net\minecraft\server\dedicated\ServerProperties.java:62: error: cannot find symbol
    public final PropertyManager<ServerProperties>.a<Boolean> whitelistEnabled;
                                                  ^

  symbol:   class a
  location: class PropertyManager<ServerProperties>
src\minecraft\net\minecraft\client\renderer\chunk\ChunkRender.java:345: warning: non-varargs call of varargs method with inexact argument type for last parameter;
                        Reflector.callVoid(Reflector.ForgeHooksClient_setRenderLayer, null);
                                                                                      ^

  cast to Object for a varargs call
  cast to Object[] for a non-varargs call and to suppress this warning
3 errors
1 warning
==================

Traceback (most recent call last):
  File "build.py", line 265, in <module>
    main(os.path.abspath(mcp_version))
  File "build.py", line 248, in main
    recompile_side( commands, CLIENT)
  File "D:\Downloads\2019\Vivecraft_114-master-t2\Vivecraft_114-master\mcp940\runtime\mcp.py", line 143, in recompile_side
    commands.recompile(side)
  File "D:\Downloads\2019\Vivecraft_114-master-t2\Vivecraft_114-master\mcp940\runtime\commands.py", line 1646, in recompile
    self.runcmd(forkcmd, log_file=pathlog[side])
  File "D:\Downloads\2019\Vivecraft_114-master-t2\Vivecraft_114-master\mcp940\runtime\commands.py", line 1695, in runcmd
    raise CalledProcessError(process.returncode, forkcmd, output)
```

**Comment by Techjar** [comment]
Who said this actually builds yet?

**Comment by Techjar** [comment]
Even if it did, you really don't want to use it. Trust me. Literally everything is broken.

**Comment by joycourier** [comment]
How can one be smart enough to navigate through github and run a batch file but dumb enough to tell the devs their indev build doesn't work

**Comment by jrbudda** [comment]
it should work at this point
